---
# Configure sudo

- name: system packages | install sudo
  become: true
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - sudo

- name: sudo | enable sudoers.d
  become: true
  lineinfile:
    backup: true
    dest: /etc/sudoers
    line: '#includedir /etc/sudoers.d'
    state: present
    validate: /usr/sbin/visudo -cf %s

- name: sudo | setup individual users and commands
  become: true
  template:
    src: sudoers-individual_commands.j2
    dest: /etc/sudoers.d/sudoers-individual_commands
    backup: false
    validate: /usr/sbin/visudo -cf %s
    mode: 0644
  when: sudoers_individual_commands | default([])
